SET(SENSOR_SOURCES
	sensors/dhtsensor.cpp
	sensors/bmpsensor.cpp
	sensors/bmp085sensor.cpp
	sensors/bmp280sensor.cpp
	sensors/ccs811sensor.cpp
	sensors/apds9301sensor.cpp
	sensors/sht31sensor.cpp
	sensors/sgp30sensor.cpp
)