SET(LWIOT_PORT_DIR ports/freertos)
SET(LWIOT_PORT_SRCS
${LWIOT_PORT_DIR}/rtos.c)
SET(LWIOT_PORT_HEADERS
${LWIOT_PORT_DIR}/arch.h)
SET(FREERTOS_DIR "${PROJECT_SOURCE_DIR}/external/freertos" CACHE STRING "FreeRTOS directory")

SET(FREERTOS_CONFIG_DIR "${PROJECT_SOURCE_DIR}/external/freertos/config" CACHE STRING "FreeRTOS config directory")

SET(LWIOT_PORT_INCLUDE_DIR
${PROJECT_SOURCE_DIR}/source/ports/freertos
${FREERTOS_CONFIG_DIR}
${FREERTOS_DIR}/Source/include
${FREERTOS_DIR}/Source/portable/${COMPILER}/${PORT}
)

SET(HAVE_RTOS True)

if(${PORT} MATCHES "unix")
	SET(LWIOT_PORT_SRCS ${LWIOT_PORT_SRCS} ${LWIOT_PORT_DIR}/unix.c)
	find_package(Threads REQUIRED)
	SET(LWIOT_SYSTEM_LIBS ${PROJECT_SOURCE_DIR}/external/freertos/lib/libfreertos.a ${CMAKE_THREAD_LIBS_INIT} ${LWIOT_SYSTEM_LIBS})
endif()
