if(WIN32)
	include (${PROJECT_SOURCE_DIR}/cmake/win32.cmake)
elseif(FREERTOS)
    if(NOT FREERTOS_MANUAL)
        include (${PROJECT_SOURCE_DIR}/cmake/freertos.cmake)
    endif()
	include(${PROJECT_SOURCE_DIR}/cmake/freertos-type-check.cmake)
elseif(UNIX)
	include (${PROJECT_SOURCE_DIR}/cmake/unix.cmake)
endif()
