SET(LWIOT_PORT_DIR ports/unix)
SET(LWIOT_PORT_SRCS
${LWIOT_PORT_DIR}/unix.c
ports/thread.cpp)
SET(LWIOT_PORT_HEADERS
${LWIOT_PORT_DIR}/arch.h)
SET(LWIOT_PORT_INCLUDE_DIR ${PROJECT_SOURCE_DIR}/source/ports/unix)

find_package(Threads REQUIRED)
SET(LWIOT_SYSTEM_LIBS ${LWIOT_SYSTEM_LIBS} ${CMAKE_THREAD_LIBS_INIT})
