
SET(PORT_INCLUDE_DIR
	${PROJECT_SOURCE_DIR}/source/platform/ports/win32
	${PROJECT_SOURCE_DIR}/source/platform/hosted/include
)

SET(PLATFORM_DIRECTORY ${PROJECT_SOURCE_DIR}/source/platform/win32)

find_package(Threads REQUIRED)
SET(LWIOT_SYSTEM_LIBS ${LWIOT_SYSTEM_LIBS} ${CMAKE_THREAD_LIBS_INIT})

SET(HAVE_JSON True CACHE BOOL "Build JSON library")
SET(HAVE_NETWORKING True)

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ")
SET(CONFIG_BUILD_TESTS True)
