SET(LWIOT_PORT_DIR ports/win32)

SET(LWIOT_PORT_SRCS
	${LWIOT_PORT_DIR}/win32.c
	soc/win32.cpp
)
SET(LWIOT_PORT_HEADERS ${LWIOT_PORT_DIR}/lwiot_arch.h)
SET(LWIOT_PORT_INCLUDE_DIRECTORIES ${PROJECT_SOURCE_DIR}/source/ports/win32 ${PROJECT_SOURCE_DIR}/include/asm/hosted)

find_package(Threads REQUIRED)
SET(LWIOT_SYSTEM_LIBS ${LWIOT_SYSTEM_LIBS} ${CMAKE_THREAD_LIBS_INIT})
